import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Warkomi",
  description: "Generated by Tupix",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="no-scrollbar bg-[#f0f0f0]">
      <body className={`${outfit.className}`}>
          <Toaster />
          {children}
      </body>
    </html>
  );
}
